### ISSUE TITLE
Not an issue. Read & Close.

### ISSUE THREAD

**Issue by iamsudip** [dhirajt/wishme-thankyou#3]
Good work. Take a look at this:
https://github.com/iamsudip/bdthankall/blob/master/bdthankall.py
All you have to do is: you have to install fbconsole(sudo pip install fbconsole)

**Comment by dhirajt** [comment]
@iamsudip actually i could have used external projects like https://github.com/kennethreitz/requests and https://github.com/jgorset/facepy but i wanted it to have no external dependency. I would implement a less bloated version with dependencies in a few days. Thanks for the encouragement :+1:
